=== franbeago17/Proyectos-LMSGI/Proyectos LMSGI/src/Tema4/EjerciciosDTD/Ejercicio1.dtd
<!ELEMENT placasBase (placa)*>
<!ELEMENT placa (componentes)>
<!ELEMENT componentes (microprocesador?, memoria+, modelo?,fabricante)*>
<!ELEMENT microprocesador (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT fabricante (Asus | Intel)*>
<!ELEMENT Asus EMPTY>
<!ELEMENT Intel EMPTY>

=== franbeago17/Proyectos-LMSGI/Proyectos LMSGI/src/Tema4/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placasBase SYSTEM "Ejercicio1.dtd">

<placasBase>
	<placa>
		<componentes>
			<microprocesador>CPU LGA1151 Intel Core 8Âª Generacion</microprocesador>
			<memoria>64gb</memoria>
			<modelo>TUF H370-PRO Gaming</modelo>
			<fabricante><Asus/></fabricante>
		</componentes>
	</placa>
	<placa>
		<componentes>
			<microprocesador>CPU LGA1151 Serial ATA III</microprocesador><
			<memoria>64gb</memoria>
			<modelo>Gigabyte GA-H110M-S2H</modelo>
			<fabricante><Intel/></fabricante>
		</componentes>
	</placa>
</placasBase>
