<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trofeosFutbolyGanadores [
<!ELEMENT trofeosFutbolyGanadores (trofeos?, ganadores+)*>
<!ELEMENT trofeos (champions, liga, copaDelRey)*>
<!ELEMENT ganadores (#PCDATA|equipos)*>
<!ELEMENT equipos (#PCDATA)>
<!ELEMENT champions EMPTY>
<!ELEMENT liga EMPTY>
<!ELEMENT copaDelRey EMPTY>
<!ENTITY % caracteristicas "<!ATTLIST ganadores nombre CDATA #REQUIRED 
												añoNacimiento (1960 | 1961 | 1962 | 1963 | 1964 | 1965) #IMPLIED
												codigo ID #REQUIRED
												estado NMTOKEN #FIXED 'activo'>">     <!--Si aparece tiene que ser el valor dado(activo)-->
<!ENTITY liga "Liga Española">
<!ATTLIST liga codigoDeReferencia IDREFS #REQUIRED>
<!ATTLIST champions codigoDeReferencia IDREFS #REQUIRED>
<!ATTLIST copaDelRey codigoDeReferencia IDREF #REQUIRED>
%caracteristicas;
]>
<trofeosFutbolyGanadores>
	<trofeos>
		<champions codigoDeReferencia= "ARM MB"/>
		<liga codigoDeReferencia= "GAM MB ARM"/>
		<copaDelRey codigoDeReferencia= "GAM"/>
	</trofeos>
	<ganadores nombre= "Asensio" añoNacimiento= "1960" codigo= "ARM" estado= "activo">
		<equipos>Real Madrid (&liga;)</equipos>
	</ganadores>
	<ganadores nombre= "Messi" añoNacimiento= "1962" codigo= "MB" estado= "activo">
		<equipos>FC Barcelona (&liga;)</equipos>
	</ganadores>
	<ganadores nombre= "Griezman" añoNacimiento= "1964" codigo= "GAM" estado= "activo">
		<equipos>Atletico de Madrid (&liga;)</equipos>
	</ganadores>
</trofeosFutbolyGanadores>




