=== franbeago17/Proyectos-LMSGI/Proyectos LMSGI/ExamenLMSGI2018.dtd
<!ELEMENT onePiece (personajes*, combatesGanados, combatesGrupalesGanados*)>
<!ELEMENT personajes (personalidad+, ambiciones?, (lugarNacimiento | rutaTomada)*)*>
<!ELEMENT combatesGanados EMPTY>
<!ELEMENT combatesGrupalesGanados EMPTY>
<!ELEMENT personalidad (#PCDATA)>
<!ELEMENT ambiciones (#PCDATA|posibilidades)*>
<!ELEMENT posibilidades (#PCDATA)>
<!ELEMENT lugarNacimiento (#PCDATA)>
<!ELEMENT rutaTomada (#PCDATA)>
<!ENTITY % caracteristicas "<!ATTLIST personajes nombre CDATA #REQUIRED
												puestoTripulacion CDATA #IMPLIED
												edad (17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25) #IMPLIED
												codigo ID #REQUIRED
												estadoTripulacion NMTOKEN #FIXED 'activo'>">
<!ENTITY ruta "El Grand Line.">
<!ATTLIST combatesGanados victorias CDATA #REQUIRED
						  codigoReferencia IDREF #REQUIRED>
<!ATTLIST combatesGrupalesGanados victoriasGrupales CDATA #REQUIRED
								  codigoReferenciaGrupal IDREFS #REQUIRED>
%caracteristicas;

=== franbeago17/Proyectos-LMSGI/Proyectos LMSGI/ExamenLMGSI2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE onePiece SYSTEM "ExamenLMSGI2018.dtd">

<onePiece>
	<personajes nombre= "Moenkey D. Luffy" edad= "17" puestoTripulacion= "Capitán" codigo= "MDL" estadoTripulacion= "activo">
		<personalidad>Agresiva</personalidad>
		<ambiciones>
			Llegar a ser el Rey de los Piratas.
			<posibilidades>Muchas</posibilidades>
		</ambiciones>
		<rutaTomada>&ruta;</rutaTomada>
	</personajes>
	<personajes nombre= "Roronoa Zoro" edad= "23" puestoTripulacion= "Espadachín" codigo= "RZ" estadoTripulacion= "activo">
		<personalidad>Agresiva</personalidad>
		<ambiciones>
			Llegar a ser el mejor espadachín del mundo.
			<posibilidades>Muchas</posibilidades>
		</ambiciones>
		<lugarNacimiento>Suroeste de la Península.</lugarNacimiento>
	</personajes>
	<personajes nombre= "Nami" edad= "21" puestoTripulacion= "Vigía" codigo= "N" estadoTripulacion= "activo">
		<personalidad>Calmada</personalidad>
		<rutaTomada>&ruta;</rutaTomada>
	</personajes>
	<personajes nombre= "Nico Robin" edad= "19" puestoTripulacion= "Vigilante" codigo= "NR" estadoTripulacion= "activo">
		<personalidad>Amable</personalidad>
		<rutaTomada>&ruta;</rutaTomada>
	</personajes>
	<personajes nombre= "Kuroashi no Sanji" edad= "25" puestoTripulacion= "Cocinero" codigo= "KNS" estadoTripulacion= "activo">
		<personalidad>Agresiva</personalidad>
		<ambiciones>
			Llegar a ser el mejor cocinero del mundo.
			<posibilidades>Muchas</posibilidades>
		</ambiciones>
		<lugarNacimiento>Este de la Península.</lugarNacimiento>
	</personajes>
	<combatesGanados victorias= "56" codigoReferencia= "MDL"/>
	<combatesGrupalesGanados victoriasGrupales= "32" codigoReferenciaGrupal= "MDL KNS"/>
</onePiece>
