<?xml version="1.0" encoding="UTF-8"?>


 los comentarios son escritos entre los símbolos  <!--    -->.


	? -> Un elemento puede aparecer 0 ó 1 vez.
	* -> Un elemento puede aparecer de 0 a una cantidad ilimitada de veces.
	+ -> Un elemento puede aparecer de 1 a una cantidad ilimitada de veces.
	
	
	Los atributos de un elemento se pueden declarar en DTD, utilizando el tag <!ATTLIST>. La sintaxis a seguir es:

	<!ATTLIST nombreElemento nombreAtributo tipoAtributo caracter>
	
	Vamos a centrarnos en los tipos disponibles para el "caracter":
	
	Un valor de texto significará simplemente un valor por defecto.
	
	#IMPLIED. El atributo es opcional
	
	#REQUIRED. El atributo es obligatorio, pero no tiene valor por defecto.
	
	#FIXED. El atributo es obligatorio y tiene por defecto un valor, el único que puede tomar.
	
	Los valores para "tipoAtributo" son:
	
	CDATA. Caracteres sin etiquetas.
	
	ENTITY. Una entidad, que se declarará en el DTD. No estudiaremos las entidades hasta un poco más adelante.
	
	ENTITIES. Lista de nombres de entidades, que se deben especificar en el DTD.
	
	Enumeración. Lista de valores excluyentes entre si. Se puede elegir uno de entre todos.
	
	ID. Identificador único de un elemento en el XML.
	
	IDREF. Referencia a un identificador existente. El valor del campo debe comenzar por letra y, a continuación, puede contener los caracteres válidos en los campos de tipo NMTOKEN.
	
	IDREFS. Varios referencias a identificadores existentes.
	
	NMTOKEN. Nombre sin espacios en blanco en su interior. Los caracteres permitidos en el valor del campo de tipo NMTOKEN son letras, digitos, el punto, el guión, el subrayado y los dos puntos.
	
	NMTOKENS. Lista de nombres con espacios en blanco en su interior.
	
	NOTATION. Notación, que debe ser declarada en el DTD.
	
	
	
	
	
	
	
	
	
	Entidad general interna. Sirve para crear un alias dentro del mismo fichero DTD. Ejemplo:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marvel [
  <!ELEMENT marvel (superheroe*)>
  <!ELEMENT superheroe (#PCDATA)>
  <!ENTITY marvel "Ediciones Marvel">
]>
<marvel>
  <superheroe>Thor el de &marvel;</superheroe>
  <superheroe>Hulk</superheroe>
<superheroe>Iron Man</superheroe>
</marvel>








Entidad parámetro. La entidad es en realidad un alias para un código que utilizamos dentro del mismo DTD. Esto es muy utilizado para la reutilización de atributos entre varios elementos. Ejemplo:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marvel [
  <!ENTITY marvel "Ediciones Marvel">
  <!ENTITY vengadores SYSTEM "superheroes.txt">
  <!ENTITY % caracteristicasHeroe "<!ATTLIST superheroe nombre CDATA #REQUIRED color CDATA #IMPLIED>">

  <!ELEMENT marvel (superheroe)>
  <!ELEMENT superheroe (#PCDATA)>
  %caracteristicasHeroe;
]>
<marvel>
  <superheroe nombre="Thor" color="azul">Su historia es muy buena</superheroe>
</marvel>









